[workspace]
members = [
  "aommap"
]


[workspace.package]
version = "0.0.0"
edition = "2021"
repository = "https://github.com/al8n/aommap"
homepage = "https://github.com/al8n/aommap"
license = "Apache-2.0/MIT"

